import type { ReviewResult } from "@/types";

const categoryEmoji: Record<string, string> = {
  bug: "BUG",
  security: "SEC",
  performance: "PERF",
  style: "STYLE",
};

const severityEmoji: Record<string, string> = {
  critical: "CRITICAL",
  warning: "WARNING",
  info: "INFO",
  praise: "PRAISE",
};

export function generateMarkdown(review: ReviewResult): string {
  const lines: string[] = [];

  lines.push("# AI Code Review");
  lines.push("");
  lines.push(`**Score:** ${review.score}/100`);
  lines.push(`**Verdict:** ${review.verdict.replace(/_/g, " ").toUpperCase()}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(review.summary);
  lines.push("");

  if (review.annotations.length > 0) {
    lines.push("## Annotations");
    lines.push("");

    for (const annotation of review.annotations) {
      const category = categoryEmoji[annotation.category] || annotation.category;
      const severity = severityEmoji[annotation.severity] || annotation.severity;
      const lineRef =
        annotation.line_start === annotation.line_end
          ? `Line ${annotation.line_start}`
          : `Lines ${annotation.line_start}-${annotation.line_end}`;

      lines.push(`### [${category}] [${severity}] ${annotation.title}`);
      lines.push("");
      lines.push(`**${lineRef}**`);
      lines.push("");
      lines.push(annotation.description);
      lines.push("");

      if (annotation.suggestion) {
        lines.push("**Suggested fix:**");
        lines.push("```");
        lines.push(annotation.suggestion);
        lines.push("```");
        lines.push("");
      }
    }
  }

  lines.push("---");
  lines.push("*Generated by AI Code Review Agent*");

  return lines.join("\n");
}
